export const API_ERROR_CODE = {
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  FORBIDDEN_ROLE: 'FORBIDDEN_ROLE',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  COURSE_NOT_FOUND: 'COURSE_NOT_FOUND',
  COURSE_NOT_OWNED: 'COURSE_NOT_OWNED',
  MODULE_NOT_FOUND: 'MODULE_NOT_FOUND',
  LESSON_NOT_FOUND: 'LESSON_NOT_FOUND',
  INVALID_WEBHOOK_SIGNATURE: 'INVALID_WEBHOOK_SIGNATURE',
  LESSON_NOT_ENROLLED: 'LESSON_NOT_ENROLLED',
  COURSE_NOT_PUBLISHED: 'COURSE_NOT_PUBLISHED',
  PAID_COURSE_REQUIRES_CHECKOUT: 'PAID_COURSE_REQUIRES_CHECKOUT',
} as const;

export type ApiErrorCode = (typeof API_ERROR_CODE)[keyof typeof API_ERROR_CODE];
