export const API_ERROR_CODE = {
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  FORBIDDEN_ROLE: 'FORBIDDEN_ROLE',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  COURSE_NOT_FOUND: 'COURSE_NOT_FOUND',
  COURSE_NOT_OWNED: 'COURSE_NOT_OWNED',
  MODULE_NOT_FOUND: 'MODULE_NOT_FOUND',
  LESSON_NOT_FOUND: 'LESSON_NOT_FOUND',
  INVALID_WEBHOOK_SIGNATURE: 'INVALID_WEBHOOK_SIGNATURE',
  LESSON_NOT_ENROLLED: 'LESSON_NOT_ENROLLED',
  COURSE_NOT_PUBLISHED: 'COURSE_NOT_PUBLISHED',
  PAID_COURSE_REQUIRES_CHECKOUT: 'PAID_COURSE_REQUIRES_CHECKOUT',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  CANNOT_CHANGE_OWN_ROLE: 'CANNOT_CHANGE_OWN_ROLE',
  ASSESSMENT_NOT_FOUND: 'ASSESSMENT_NOT_FOUND',
  ASSESSMENT_NOT_AVAILABLE: 'ASSESSMENT_NOT_AVAILABLE',
  ASSESSMENT_COURSE_NOT_COMPLETE: 'ASSESSMENT_COURSE_NOT_COMPLETE',
  ASSESSMENT_INVALID_SUBMISSION: 'ASSESSMENT_INVALID_SUBMISSION',
} as const;

export type ApiErrorCode = (typeof API_ERROR_CODE)[keyof typeof API_ERROR_CODE];
